//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scholarship_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class availed
    {
        public long Id { get; set; }
        public long student_id { get; set; }
        public long listing_id { get; set; }
    
        public virtual listing listing { get; set; }
        public virtual student student { get; set; }
    }
}
