//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scholarship_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class listing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public listing()
        {
            this.availeds = new HashSet<availed>();
        }
    
        public long Id { get; set; }
        public string GivenBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<long> NoAvailable { get; set; }
        public Nullable<long> student_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<availed> availeds { get; set; }
        public virtual student student { get; set; }
    }
}
