//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scholarship_app.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class scholarship_details
    {
        public long Id { get; set; }
        public long student_id { get; set; }
        public Nullable<long> amount { get; set; }
        public string address { get; set; }
        public string reason { get; set; }
        [DefaultValue("Pending")]
        public string status { get; set; }
    
        public virtual student student { get; set; }
    }
}
