//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scholarship_app.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.scholarship_details = new HashSet<scholarship_details>();
            this.availeds = new HashSet<availed>();
            this.listings = new HashSet<listing>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }


        [Required(ErrorMessage = "You must provide a valid Email Id")]
        [RegularExpression(@"^\S+@\S+\.\S+$", ErrorMessage = "Not a valid Email Id")]
       
        public string Email { get; set; }
        [Display(Name = "Home Phone")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]

        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public string ScholarshipCategory { get; set; }

        [HiddenInput(DisplayValue = false)]
        public string StateofDomicile { get; set; }

        [Required(ErrorMessage = "You must provide a Bank AC Number")]
       
        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Not a valid Bank AC Number")]

        public string BankACNumber { get; set; }

        public string BankIFSCCode { get; set; }


        [Required(ErrorMessage = "You must provide a valid Bank Name")]
        [RegularExpression(@"^[a-zA-z]$", ErrorMessage = "Not a valid Bank Name")]
        public string BankName { get; set; }

        [HiddenInput(DisplayValue = false)]
        public string Gender { get; set; }
        public string SchemeType { get; set; }
        public string IdentificationDetail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scholarship_details> scholarship_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<availed> availeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<listing> listings { get; set; }
    }
}
